# cam_model: EquidistantCamera
# cam_width: 1280
# cam_height: 1024
# scale: 1.0
# cam_fx: 540.645056202188
# cam_fy: 539.8545023658869
# cam_cx: 626.4125666883942
# cam_cy: 523.947634226782
# k1: -0.07015146608431883
# k2: 0.008586142263125124
# k3: -0.021968993685891842
# k4: 0.007442211946112636
cam_model: Pinhole
cam_width: 2448
cam_height: 2048
scale: 0.5
cam_fx: 1453.88
cam_fy: 1452.85
cam_cx: 1182.53
cam_cy: 1045.82 
cam_d0: -0.052
cam_d1: 0.1168
cam_d2: 0.0015
cam_d3: 0.00013