cam_model: Pinhole
cam_width: 2448
cam_height: 2048
scale: 0.25
cam_fx: 2340.84038885597
cam_fy: 2343.90144344669
cam_cx: 1212.60625557832
cam_cy: 1040.13711412500
cam_d0: -0.0484912635635976
cam_d1: 0.0932898652373741
cam_d2: 0.000399426275334593
cam_d3: 0.000470330631945937